services:
  lapland_backend:
    build: ./backend
    container_name: lapland_backend
    privileged: true
    security_opt:
      - seccomp:unconfined
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=lapland_db
      - DB_PORT=3306
      - DB_USER=lapland
      - DB_PASSWORD=lapland_pass
      - DB_NAME=lapland
    depends_on:
      - db

  lapland_frontend:
    build: ./frontend
    container_name: lapland_frontend
    ports:
      - "3030:80"
    depends_on:
      - lapland_backend

  db:
    image: mariadb:11
    container_name: lapland_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=lapland
      - MYSQL_USER=lapland
      - MYSQL_PASSWORD=lapland_pass
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

  

volumes:
  mariadb_data:



