import { useState, useMemo, useEffect } from "react";
import ConfirmDialog from "./ConfirmDialog";
const EUR_TO_PLN = 4.35;
const COLORS = ["#00c896","#f0a500","#4ca0e0","#e05555","#a78bfa","#fb923c","#34d399","#60a5fa"];
function getAvatarColor(id) { return COLORS[(id - 1) % COLORS.length]; }
function initials(name) { return name.slice(0, 2).toUpperCase(); }
export default function Finanse({ members, expenses, currentUser, onAddExpense, onUpdateExpense, onDeleteExpense }) {
  const [editingId, setEditingId] = useState(null);
  const [form, setForm] = useState({ title: "", amount: "", currency: "PLN", payerId: members.length > 0 ? members[0].id.toString() : "", splitIds: members.map(m => m.id) });
  const [showForm, setShowForm] = useState(false);
  const [saving, setSaving] = useState(false);
  const [deleteConfirm, setDeleteConfirm] = useState(null);
  useEffect(() => { if (members.length > 0 && !form.payerId) { setForm(f => ({ ...f, payerId: members[0].id.toString(), splitIds: members.map(m => m.id) })); } }, [members, form.payerId]);
  const amountPLN = form.currency === "EUR" ? (parseFloat(form.amount) || 0) * EUR_TO_PLN : parseFloat(form.amount) || 0;
  function toggleSplit(id) { setForm(f => ({ ...f, splitIds: f.splitIds.includes(id) ? f.splitIds.filter(x => x !== id) : [...f.splitIds, id] })); }
  function startEdit(e) { setEditingId(e.id); let loadAmount = e.amount; const currency = e.currency || "PLN"; if (currency === "EUR" && e.original_amount) loadAmount = e.original_amount; setForm({ title: e.title, amount: loadAmount, currency: currency, payerId: e.payerId.toString(), splitIds: e.splitIds && e.splitIds.length > 0 ? e.splitIds : members.map(m => m.id) }); setShowForm(true); }
  function cancelEdit() { setEditingId(null); setForm({ title: "", amount: "", currency: "PLN", payerId: members.length > 0 ? members[0].id.toString() : "", splitIds: members.map(m => m.id) }); setShowForm(false); }
  async function saveExpense() { if (!form.title.trim() || !form.amount || form.splitIds.length === 0 || !form.payerId) return; setSaving(true); const originalAmount = Math.round(parseFloat(form.amount) * 100) / 100; const convertedAmount = Math.round(amountPLN * 100) / 100; if (isNaN(originalAmount) || originalAmount <= 0) { setSaving(false); alert("Kwota"); return; } const expenseData = { title: form.title.trim(), amount: convertedAmount, originalAmount, currency: form.currency, payerId: parseInt(form.payerId), splitIds: form.splitIds.map(id => parseInt(id)) }; if (editingId) await onUpdateExpense(editingId, expenseData); else await onAddExpense(expenseData); setEditingId(null); setForm({ title: "", amount: "", currency: "PLN", payerId: members.length > 0 ? members[0].id.toString() : "", splitIds: members.map(m => m.id) }); setShowForm(false); setSaving(false); }
  const handleDeleteConfirmed = () => { if (!deleteConfirm) return; onDeleteExpense(deleteConfirm.id); setDeleteConfirm(null); };
  const balances = useMemo(() => { const bal = {}; members.forEach(m => (bal[m.id] = 0)); expenses.forEach(e => { const splits = e.splitIds?.length > 0 ? e.splitIds : members.map(m => m.id); const share = e.amount / splits.length; splits.forEach(id => { bal[id] = (bal[id] || 0) - share; }); if (e.payerId) bal[e.payerId] = (bal[e.payerId] || 0) + e.amount; }); return bal; }, [expenses, members]);
  const transfers = useMemo(() => { const debtors = members.map(m => ({ ...m, bal: balances[m.id] || 0 })).filter(m => m.bal < -0.01); const creditors = members.map(m => ({ ...m, bal: balances[m.id] || 0 })).filter(m => m.bal > 0.01); const result = []; let i = 0, j = 0; const d = debtors.map(x => ({ ...x })); const c = creditors.map(x => ({ ...x })); while (i < d.length && j < c.length) { const amount = Math.min(-d[i].bal, c[j].bal); result.push({ from: d[i].name, to: c[j].name, amount, fromId: d[i].id }); d[i].bal += amount; c[j].bal -= amount; if (Math.abs(d[i].bal) < 0.01) i++; if (Math.abs(c[j].bal) < 0.01) j++; } return result; }, [balances, members]);
  const getName = id => members.find(m => m.id === id)?.name || "?";
  return (<div className="finanse-container"><div className="card"><div className="card-title">💰 Bilans</div><div className="balance-grid">{members.map(m => { const b = balances[m.id] || 0; return (<div key={m.id} className="balance-item"><div style={{fontSize:"20px"}}>{initials(m.name)}</div><div>{m.name}</div><div style={{color: b>0?"green":b<0?"red":"gray"}}>{b.toFixed(2)}zł</div></div>); })}</div></div>{transfers.length > 0 && (<div className="card"><div className="card-title">→ Przelewy</div><ul>{transfers.map((t, i) => (<li key={i}>{t.from} → {t.to}: {t.amount.toFixed(2)}zł</li>))}</ul></div>)}<div className="card"><div style={{display:"flex",justifyContent:"space-between"}}><div className="card-title">Wydatki ({expenses.length})</div>{!showForm && <button onClick={() => setShowForm(true)}>+ Dodaj</button>}</div>{showForm && (<div><input value={form.title} onChange={e => setForm(f => ({...f, title: e.target.value}))} placeholder="Tytuł" /><input type="number" value={form.amount} onChange={e => setForm(f => ({...f, amount: e.target.value}))} placeholder="Kwota" /><select value={form.currency} onChange={e => setForm(f => ({...f, currency: e.target.value}))}><option>PLN</option><option>EUR</option></select><div>{members.map(m => <button key={m.id} onClick={() => setForm(f => ({...f, payerId: m.id.toString()}))} style={{background: form.payerId === m.id.toString() ? "blue" : "gray"}}>{m.name}</button>)}</div><div>{members.map(m => <label key={m.id}><input type="checkbox" checked={form.splitIds.includes(m.id)} onChange={() => toggleSplit(m.id)} />{m.name}</label>)}</div><button onClick={saveExpense} disabled={!form.payerId}>Zapisz</button><button onClick={cancelEdit}>Anuluj</button></div>)}{expenses.map(e => (<div key={e.id} style={{borderBottom:"1px solid #ccc", padding:"10px"}}><div>{e.title} - {e.amount.toFixed(2)}zł (od {getName(e.payerId)})</div><button onClick={() => startEdit(e)}>✏️</button><button onClick={() => setDeleteConfirm({id: e.id, title: e.title})}>🗑️</button></div>))}</div><ConfirmDialog isOpen={deleteConfirm !== null} title="Usunąć?" message={`Usunąć "${deleteConfirm?.title}"?`} confirmText="Usuń" cancelText="Anuluj" isDangerous={true} onConfirm={handleDeleteConfirmed} onCancel={() => setDeleteConfirm(null)} /></div>);
}
